### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by staccato** [ulnk/nfb#1]
🙉

**Comment by ulnk** [comment]
penis

**Comment by staccato** [comment]
You need to remove the node_modules from the repo.

**Comment by ulnk** [comment]
okay lol

**Comment by ulnk** [comment]
who are you btw

**Comment by staccato** [comment]
brandon

**Comment by ulnk** [comment]
do you have anything like discord so i can speak w u easier i have found something

**Comment by staccato** [comment]
hap down loool @ulnk

**Comment by staccato** [comment]
also okkk#7741
